name: client
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  provider: ^6.0.5
  mask_text_input_formatter: ^2.4.0
  pin_code_fields: ^7.4.0
  logger: ^1.1.0
  build_runner: ^2.3.3
  faker: ^2.1.0
  flutter_gen_runner: ^5.1.0+1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flavor: ^2.0.0
  flutter_dotenv: ^5.0.2
  dot_navigation_bar: ^1.0.1+4
  buttons_tabbar: ^1.3.6
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.8
  share_plus: ^6.3.0
  map_launcher: ^2.4.0
  cached_network_image: ^3.2.3
  permission_handler: ^10.2.0
  onesignal_flutter: ^3.5.0
  geocoding: ^2.0.5
  google_maps_flutter: ^2.2.5
  geolocator: ^9.0.2
  socket_io_client: ^2.0.1
  retrofit: ^4.0.1
  get_storage: ^2.1.1
  equatable: ^2.0.5
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2

  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

  shared_preferences: ^2.0.18
  flutter_secure_storage: ^8.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  retrofit_generator: ^5.0.0
  isar_generator: ^3.0.5
  
flutter:
  generate: false
  uses-material-design: true  
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/onboarding/
    - assets/images/home/
    - assets/images/shop/
    - assets/images/permission/
    - assets/env/

 
